
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package edu.cpp.cs411.parser;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int LEFTBRACKET = 40;
  public static final int PERIOD = 37;
  public static final int RIGHTBRACKET = 41;
  public static final int RIGHTPAREN = 39;
  public static final int DOUBLE = 5;
  public static final int NOTEQUAL = 30;
  public static final int GREATER = 27;
  public static final int INTERFACE = 12;
  public static final int INT = 11;
  public static final int PRINTLN = 14;
  public static final int LESS = 25;
  public static final int FOR = 8;
  public static final int MINUS = 21;
  public static final int LEFTPAREN = 38;
  public static final int SEMICOLON = 35;
  public static final int NOT = 33;
  public static final int AND = 31;
  public static final int LESSEQUAL = 26;
  public static final int OR = 32;
  public static final int COMMA = 36;
  public static final int DOUBLECONSTANT = 45;
  public static final int CLASS = 4;
  public static final int NEWARRAY = 13;
  public static final int PLUS = 20;
  public static final int IF = 9;
  public static final int ID = 48;
  public static final int INTCONSTANT = 44;
  public static final int EOF = 0;
  public static final int BOOLEAN = 2;
  public static final int RETURN = 16;
  public static final int EQUAL = 29;
  public static final int STRINGCONSTANT = 46;
  public static final int error = 1;
  public static final int MOD = 24;
  public static final int BREAK = 3;
  public static final int VOID = 18;
  public static final int READLN = 15;
  public static final int ASSIGNOP = 34;
  public static final int GREATEREQUAL = 28;
  public static final int RIGHTBRACE = 43;
  public static final int ELSE = 6;
  public static final int WHILE = 19;
  public static final int BOOLEANCONSTANT = 47;
  public static final int LEFTBRACE = 42;
  public static final int EXTENDS = 7;
  public static final int STRING = 17;
  public static final int DIVISION = 23;
  public static final int IMPLEMENTS = 10;
  public static final int MULTIPLICATION = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOOLEAN",
  "BREAK",
  "CLASS",
  "DOUBLE",
  "ELSE",
  "EXTENDS",
  "FOR",
  "IF",
  "IMPLEMENTS",
  "INT",
  "INTERFACE",
  "NEWARRAY",
  "PRINTLN",
  "READLN",
  "RETURN",
  "STRING",
  "VOID",
  "WHILE",
  "PLUS",
  "MINUS",
  "MULTIPLICATION",
  "DIVISION",
  "MOD",
  "LESS",
  "LESSEQUAL",
  "GREATER",
  "GREATEREQUAL",
  "EQUAL",
  "NOTEQUAL",
  "AND",
  "OR",
  "NOT",
  "ASSIGNOP",
  "SEMICOLON",
  "COMMA",
  "PERIOD",
  "LEFTPAREN",
  "RIGHTPAREN",
  "LEFTBRACKET",
  "RIGHTBRACKET",
  "LEFTBRACE",
  "RIGHTBRACE",
  "INTCONSTANT",
  "DOUBLECONSTANT",
  "STRINGCONSTANT",
  "BOOLEANCONSTANT",
  "ID"
  };
}

